import { createFileRoute } from "@tanstack/react-router";
import { Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { z } from "zod";
import { ProductCard } from "@/components/ProductCard";
import { categories } from "@/data/categories";
import { brands } from "@/data/brands";
import { products } from "@/data/products";

const searchSchema = z.object({ q: z.string().optional().catch(undefined), category: z.string().optional().catch(undefined) });
export const Route = createFileRoute("/shop")({ validateSearch: searchSchema, head: () => ({ meta: [{ title: "Shop the Collection — SHOW GREDI" }, { name: "description", content: "Browse SHOW GREDI's complete collection of luxury bags, watches, fragrance, footwear and accessories." }, { property: "og:title", content: "Shop the Collection — SHOW GREDI" }, { property: "og:description", content: "Explore our considered edit of modern luxury." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShopPage });

function ShopPage() {
  const search = Route.useSearch();
  const [query, setQuery] = useState(search.q ?? ""); const [category, setCategory] = useState(search.category ?? "All"); const [brand, setBrand] = useState("All"); const [sort, setSort] = useState("featured");
  const filtered = useMemo(() => products.filter((p) => (category === "All" || p.category === category) && (brand === "All" || p.brand === brand) && `${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "low" ? a.price-b.price : sort === "high" ? b.price-a.price : Number(b.featured)-Number(a.featured)), [query, category, brand, sort]);
  return <div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:py-20"><div className="border-b border-border pb-10"><p className="text-[10px] uppercase tracking-[0.28em] text-primary">The complete edit</p><h1 className="mt-3 font-display text-5xl sm:text-7xl">Shop</h1><p className="mt-3 text-sm text-muted-foreground">{filtered.length} considered pieces</p></div><div className="grid gap-8 py-8 lg:grid-cols-[230px_minmax(0,1fr)]"><aside className="space-y-6"><div className="flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-primary"><SlidersHorizontal className="h-4 w-4" /> Refine</div><label className="flex items-center border-b border-border"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the edit" className="h-12 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" /></label><Filter label="Category" value={category} onChange={setCategory} options={["All", ...categories.map((c) => c.name)]} /><Filter label="Brand" value={brand} onChange={setBrand} options={["All", ...brands]} /></aside><div><div className="mb-5 flex justify-end"><select value={sort} onChange={(e) => setSort(e.target.value)} className="min-h-11 border border-border bg-card px-3 text-xs uppercase tracking-[0.1em] outline-none"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4 lg:gap-5">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div>{filtered.length === 0 && <p className="border border-border py-20 text-center text-sm text-muted-foreground">No pieces match your selection.</p>}<div className="mt-10 flex justify-center gap-2"><span className="grid h-10 w-10 place-items-center border border-primary bg-primary text-primary-foreground">1</span></div></div></div></div>;
}
function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="block"><span className="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-11 w-full border border-border bg-card px-3 text-sm outline-none">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }